/// Integration tests for the simple-lock contract.
///
/// These tests exercise the full PSCT validation flow:
///   1. Load the generated IDL for simple-lock
///   2. Use ckb-idl-client to validate a proposed witness buffer
///      BEFORE attaching it to a transaction
///   3. Build and verify the actual CKB transaction
///
/// The IDL hash verification step is skipped in these tests because we are
/// reading the IDL directly from the build artefact on disk rather than
/// fetching it from a registry. The registry flow (fetch + verify) is
/// tested in the ckb-idl-client crate itself.
use ckb_idl_client::{IdlClient, IdlDocument, WitnessField};
use ckb_testtool::builtin::ALWAYS_SUCCESS;
use ckb_testtool::ckb_hash::blake2b_256;
use ckb_testtool::ckb_types::{bytes::Bytes, core::TransactionBuilder, packed::*, prelude::*};
use ckb_testtool::context::Context;

const MAX_CYCLES: u64 = 10_000_000;

/// Load the simple-lock IDL that was generated by #[derive(CkbWitness)].
/// The macro writes idl.json next to Cargo.toml (CARGO_MANIFEST_DIR).
fn load_simple_lock_idl() -> IdlDocument {
    // CARGO_MANIFEST_DIR for the `tests` crate is `ckb_lock_script/tests/`.
    // The IDL lives at `ckb_lock_script/contracts/simple-lock/idl.json`.
    let idl_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../contracts/simple-lock/idl.json"
    );
    let json = std::fs::read_to_string(idl_path)
        .expect("simple-lock idl.json not found — run `make build` first");

    // ckb-idl-client is still flat-only, so adapt the 0.1.0 lock-witness
    // interface fields into its legacy IdlDocument shape for PSCT coverage.
    let raw: serde_json::Value = serde_json::from_str(&json).expect("idl.json is not valid JSON");

    let witness_fields: Vec<WitnessField> =
        serde_json::from_value(raw["interfaces"][0]["fields"].clone())
            .expect("idl.json has no witness_args.lock interface fields");

    IdlDocument {
        idl_version: "0.1.0".to_string(),
        name: "simple-lock".to_string(),
        witness: witness_fields,
        description: None,
        script_version: None,
        signing: None,
    }
}

/// Encode a witness for simple-lock using the ckb-idl-derive wire format.
///
/// simple-lock has one field: `preimage: Vec<u8>` (type "bytes").
/// Wire format for bytes: 4-byte LE length prefix + payload.
fn encode_simple_lock_witness(preimage: &[u8]) -> Vec<u8> {
    let mut buf = Vec::new();
    let len = preimage.len() as u32;
    buf.extend_from_slice(&len.to_le_bytes());
    buf.extend_from_slice(preimage);
    buf
}

// ─────────────────────────────────────────────────────────────────────────────
// Witness validation tests (no CKB VM — pure client-side PSCT checks)
// ─────────────────────────────────────────────────────────────────────────────

/// A correctly encoded witness passes structural validation.
#[test]
fn test_witness_validation_passes_for_correct_encoding() {
    let idl = load_simple_lock_idl();
    let preimage = b"correct_preimage";
    let wire = encode_simple_lock_witness(preimage);

    let client = IdlClient::new();
    let result = client.validate_witness_bytes(&idl.witness, &wire);

    assert!(
        result.is_ok(),
        "valid witness should pass validation: {:?}",
        result
    );

    let fields = result.unwrap();
    assert_eq!(fields.len(), 1, "simple-lock has exactly one witness field");
    assert_eq!(fields[0].name, "preimage");

    match &fields[0].value {
        ckb_idl_client::DecodedValue::Bytes(got) => {
            assert_eq!(got.as_slice(), preimage);
        }
        other => panic!("expected Bytes, got {:?}", other),
    }
}

/// An empty preimage (zero-length bytes field) is structurally valid.
#[test]
fn test_witness_validation_passes_for_empty_preimage() {
    let idl = load_simple_lock_idl();
    let wire = encode_simple_lock_witness(&[]);

    let client = IdlClient::new();
    let result = client.validate_witness_bytes(&idl.witness, &wire);
    assert!(
        result.is_ok(),
        "empty preimage should be structurally valid"
    );
}

/// A raw byte buffer with no length prefix fails structural validation.
/// This is what a naive implementation might produce — raw bytes without
/// the 4-byte length prefix the wire format requires.
#[test]
fn test_witness_validation_fails_for_raw_bytes_without_prefix() {
    let idl = load_simple_lock_idl();
    // Raw preimage with no length prefix — only 3 bytes, less than
    // the 4 required for the length prefix of a "bytes" field.
    let bare_bytes = b"abc";

    let client = IdlClient::new();
    let result = client.validate_witness_bytes(&idl.witness, bare_bytes);

    assert!(
        result.is_err(),
        "raw bytes without length prefix should fail"
    );
    assert!(
        matches!(result, Err(ckb_idl_client::IdlError::FieldTooShort { .. })),
        "expected FieldTooShort, got {:?}",
        result
    );
}

/// Trailing bytes after a correctly decoded witness fail validation.
/// Guards against the case where a wallet attaches extra data.
#[test]
fn test_witness_validation_fails_for_trailing_bytes() {
    let idl = load_simple_lock_idl();
    let preimage = b"my_preimage";
    let mut wire = encode_simple_lock_witness(preimage);
    wire.extend_from_slice(b"junk"); // 4 extra bytes

    let client = IdlClient::new();
    let result = client.validate_witness_bytes(&idl.witness, &wire);

    assert!(
        matches!(
            result,
            Err(ckb_idl_client::IdlError::TrailingBytes { trailing: 4, .. })
        ),
        "expected TrailingBytes {{ trailing: 4 }}, got {:?}",
        result
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// Full flow: validate witness then run it through the CKB VM
// ─────────────────────────────────────────────────────────────────────────────

/// Helper: deploy simple-lock and create a cell locked by it.
/// Returns (context, out_point of the locked cell, expected_hash).
fn setup_simple_lock_cell(preimage: &[u8]) -> (Context, OutPoint, [u8; 32]) {
    let mut context = Context::default();
    let lock_out_point = context.deploy_cell_by_name("simple-lock");

    let expected_hash = blake2b_256(preimage);
    let args = Bytes::from(expected_hash.to_vec());
    let lock_script = context
        .build_script(&lock_out_point, args)
        .expect("lock script");

    let locked_cell = context.create_cell(
        CellOutput::new_builder()
            .capacity(1000u64)
            .lock(lock_script.clone())
            .build(),
        Bytes::new(),
    );

    (context, locked_cell, expected_hash)
}

/// Helper: build an always-success output to receive the capacity.
fn build_output_lock(context: &mut Context) -> Script {
    let always_success_out_point = context.deploy_cell(ALWAYS_SUCCESS.clone());
    context
        .build_script(&always_success_out_point, Bytes::new())
        .expect("always-success output lock")
}

/// PSCT flow test: validate witness bytes, then run the transaction.
///
/// This is the target developer experience:
///   wallet builds preimage → encodes witness → validates with IdlClient →
///   if valid, attaches witness to tx → submits → passes VM verification
#[test]
fn test_psct_validate_then_execute_simple_lock() {
    let preimage = b"secret_preimage_known_only_to_spender";
    let idl = load_simple_lock_idl();

    // Step 1: encode the proposed witness
    let wire = encode_simple_lock_witness(preimage);

    // Step 2: PSCT check — validate before building the transaction
    let client = IdlClient::new();
    let validated = client
        .validate_witness_bytes(&idl.witness, &wire)
        .expect("witness should be structurally valid before tx construction");

    println!("PSCT validation passed. Decoded fields:");
    for f in &validated {
        println!("  {} ({}): {:?}", f.name, f.type_, f.value);
    }

    // Step 3: now build and submit the transaction
    let (mut context, locked_cell, _) = setup_simple_lock_cell(preimage);
    let output_lock = build_output_lock(&mut context);

    let input = CellInput::new_builder()
        .previous_output(locked_cell)
        .build();
    let output = CellOutput::new_builder()
        .capacity(1000u64)
        .lock(output_lock)
        .build();

    // Wrap our wire-format preimage in WitnessArgs.lock
    let witness_args = WitnessArgs::new_builder()
        .lock(Some(Bytes::from(wire)).pack())
        .build();

    let tx = TransactionBuilder::default()
        .input(input)
        .output(output)
        .output_data(Bytes::new().pack())
        .witness(witness_args.as_bytes().pack())
        .build();
    let tx = context.complete_tx(tx);

    context
        .verify_tx(&tx, MAX_CYCLES)
        .expect("transaction should pass VM verification after PSCT check");
}

/// PSCT catches a malformed witness BEFORE it reaches the VM.
///
/// A wrong preimage (hash mismatch) would fail the VM, but that failure
/// is semantic — the VM has to execute to detect it. A completely
/// wrong wire encoding fails the PSCT structural check immediately,
/// before the VM is ever invoked.
#[test]
fn test_psct_catches_malformed_wire_before_vm() {
    let idl = load_simple_lock_idl();

    // A witness that is just raw bytes with no length prefix — wrong format.
    let malformed_wire = b"this_is_not_length_prefixed_and_has_no_prefix_at_all"[..3].to_vec();

    let client = IdlClient::new();
    let result = client.validate_witness_bytes(&idl.witness, &malformed_wire);

    assert!(
        result.is_err(),
        "malformed witness should fail PSCT validation before ever reaching the VM"
    );
    println!(
        "PSCT correctly rejected malformed witness: {}",
        result.unwrap_err()
    );
}
